name: CI

on:
  push:
    branches: [ "main" ]
  schedule:
  - cron: "0 */2 * * *"

  workflow_dispatch:

jobs:
  build:
    concurrency:
      group: ${{ matrix.variant }}
      cancel-in-progress: false

    strategy:
      matrix:
        variant: [ rv64gc-O3-thinlto, rv64gc-Os-thinlto, rv64gczxx-O3-thinlto ]

    runs-on: ${{ matrix.variant }}

    permissions:
      issues: write 

    steps:
      - uses: dtcxzyw/checkout@main

      - name: Create work space
        run: ./setup-work-space.sh ${{ vars.BASE_DIR }}/${{ matrix.variant }}

      - name: Update LLVM
        run: ${{ github.workspace }}/update-llvm.sh
        working-directory: ${{ vars.BASE_DIR }}/${{ matrix.variant }}
        
      - name: Check force-rebuild flag
        if: github.event_name != 'schedule'
        run: echo "FORCE_REBUILD=1" >> $GITHUB_ENV

      - name: Update llvm-test-suite
        run: ${{ github.workspace }}/update-llvm-test-suite.sh
        working-directory: ${{ vars.BASE_DIR }}/${{ matrix.variant }}

      - name: Update llvm-lnt
        run: ${{ github.workspace }}/update-llvm-lnt.sh
        working-directory: ${{ vars.BASE_DIR }}/${{ matrix.variant }}

      - name: Build LLVM
        run: ${{ github.workspace }}/build-llvm.sh ${{ github.workspace }}
        working-directory: ${{ vars.BASE_DIR }}/${{ matrix.variant }}

      - name: Build LLVM Test Suite
        id: test
        run: ${{ github.workspace }}/build-llvm-test-suite.sh ${{ github.workspace }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ github.run_id }} ${{ matrix.variant }}
        working-directory: ${{ vars.BASE_DIR }}/${{ matrix.variant }}
        
      - name: Report
        uses: JasonEtco/create-an-issue@v2
        if: steps.test.outputs.SHOULD_OPEN_ISSUE == '1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: issue.md

      - name: Archive artifacts
        uses: dtcxzyw/upload-artifact@main
        with:
          name: artifacts-${{ matrix.variant }}
          path: ${{ vars.BASE_DIR }}/${{ matrix.variant }}/artifacts
