name: Pre-Commit CI

on:
  pull_request:
    types: [opened, reopened]
  #issue_comment:
  #  types: [opened]
  
env:
  BASE_DIR: /home/dtcxzyw/llvm-ci/

jobs:
  build:
    concurrency:
      group: ${{ matrix.variant }}
      cancel-in-progress: false

    strategy:
      matrix:
        variant: [ rv64gc-O3-thinlto, rv64gc-Os-thinlto ]

    runs-on: ${{ matrix.variant }}
    permissions:
      issues: write 
      pull-requests: write

    steps:
      - uses: dtcxzyw/checkout@main

      - name: Create work space
        run: ${{ github.workspace }}/setup-work-space.sh ${{ env.BASE_DIR }}/${{ matrix.variant }}

      - name: Setup patch
        run: ${{ github.workspace }}/apply-pre-commit-patch.sh ${{ github.workspace }}
        working-directory: ${{ env.BASE_DIR }}/${{ matrix.variant }}

      - name: Build LLVM
        run: ${{ github.workspace }}/build-llvm.sh ${{ github.workspace }}
        working-directory: ${{ env.BASE_DIR }}/${{ matrix.variant }}

      - name: Build LLVM Test Suite
        run: ${{ github.workspace }}/build-llvm-test-suite.sh ${{ github.workspace }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ github.run_id }} ${{ matrix.variant }}
        working-directory: ${{ env.BASE_DIR }}/${{ matrix.variant }}

      - name: Report
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr-comment.md
        
      - name: Archive artifacts
        uses: dtcxzyw/upload-artifact@main
        with:
          name: artifacts-${{ matrix.variant }}
          path: ${{ env.BASE_DIR }}/${{ matrix.variant }}/artifacts
          
